/**
 * The Magento ACL resource tree behind Roles > Role Resources.
 *
 * Scraped node-for-node off the live source's jstree at
 * `/admin/admin/user_role/editrole/rid/1/` (263 nodes, real `Magento_*::*`
 * resource ids, source order preserved). `level` is the node's depth in that
 * tree; the form renders it as an indented checkbox list.
 */
export const ACL_RESOURCES = [
  { id: "Magento_Backend::dashboard", label: "Dashboard", level: 0 },
  { id: "Magento_Analytics::analytics", label: "Analytics", level: 0 },
  { id: "Magento_Analytics::analytics_api", label: "API", level: 1 },
  { id: "Magento_Sales::sales", label: "Sales", level: 0 },
  { id: "Magento_Sales::sales_operation", label: "Operations", level: 1 },
  { id: "Magento_Sales::sales_order", label: "Orders", level: 2 },
  { id: "Magento_Sales::actions", label: "Actions", level: 3 },
  { id: "Magento_Sales::create", label: "Create", level: 4 },
  { id: "Magento_Sales::actions_view", label: "View", level: 4 },
  { id: "Magento_Sales::email", label: "Send Order Email", level: 4 },
  { id: "Magento_Sales::reorder", label: "Reorder", level: 4 },
  { id: "Magento_Sales::actions_edit", label: "Edit", level: 4 },
  { id: "Magento_Sales::cancel", label: "Cancel", level: 4 },
  { id: "Magento_Sales::review_payment", label: "Accept or Deny Payment", level: 4 },
  { id: "Magento_Sales::capture", label: "Capture", level: 4 },
  { id: "Magento_Sales::invoice", label: "Invoice", level: 4 },
  { id: "Magento_Sales::creditmemo", label: "Credit Memos", level: 4 },
  { id: "Magento_Sales::hold", label: "Hold", level: 4 },
  { id: "Magento_Sales::unhold", label: "Unhold", level: 4 },
  { id: "Magento_Sales::ship", label: "Ship", level: 4 },
  { id: "Magento_Sales::comment", label: "Comment", level: 4 },
  { id: "Magento_Sales::emails", label: "Send Sales Emails", level: 4 },
  { id: "Magento_Paypal::authorization", label: "Payment Amount Authorization", level: 4 },
  { id: "Magento_Sales::sales_invoice", label: "Invoices", level: 2 },
  { id: "Magento_Sales::shipment", label: "Shipments", level: 2 },
  { id: "Magento_Sales::sales_creditmemo", label: "Credit Memos", level: 2 },
  { id: "Magento_Paypal::billing_agreement", label: "Billing Agreements", level: 2 },
  { id: "Magento_Paypal::billing_agreement_actions", label: "Actions", level: 3 },
  { id: "Magento_Paypal::billing_agreement_actions_view", label: "View", level: 4 },
  { id: "Magento_Paypal::actions_manage", label: "Manage", level: 4 },
  { id: "Magento_Paypal::use", label: "Place Order Using Billing Agreements", level: 4 },
  { id: "Magento_Sales::transactions", label: "Transactions", level: 2 },
  { id: "Magento_Sales::transactions_fetch", label: "Fetch", level: 3 },
  { id: "Magento_Catalog::catalog", label: "Catalog", level: 0 },
  { id: "Magento_Catalog::catalog_inventory", label: "Inventory", level: 1 },
  { id: "Magento_Catalog::products", label: "Products", level: 2 },
  { id: "Magento_Catalog::update_attributes", label: "Mass Update Attributes", level: 3 },
  { id: "Magento_Catalog::edit_product_design", label: "Edit Product Design", level: 3 },
  { id: "Magento_Catalog::categories", label: "Categories", level: 2 },
  { id: "Magento_Catalog::edit_category_design", label: "Edit Category Design", level: 3 },
  { id: "Magento_Customer::customer", label: "Customers", level: 0 },
  { id: "Magento_Customer::manage", label: "All Customers", level: 1 },
  { id: "Magento_Customer::actions", label: "Actions", level: 2 },
  { id: "Magento_Customer::delete", label: "Delete", level: 3 },
  { id: "Magento_Customer::reset_password", label: "Reset password", level: 3 },
  { id: "Magento_Customer::invalidate_tokens", label: "Invalidate tokens", level: 3 },
  { id: "Magento_LoginAsCustomer::allow_shopping_assistance", label: "Remote shopping assistance opt-in", level: 3 },
  { id: "Magento_Customer::online", label: "Now Online", level: 1 },
  { id: "Magento_Customer::group", label: "Customer Groups", level: 1 },
  { id: "Magento_LoginAsCustomer::login", label: "Login as Customer", level: 1 },
  { id: "Magento_LoginAsCustomerLog::login_log", label: "View Login as Customer Log", level: 2 },
  { id: "Magento_Cart::cart", label: "Carts", level: 0 },
  { id: "Magento_Cart::manage", label: "Manage carts", level: 1 },
  { id: "Magento_Backend::myaccount", label: "My Account", level: 0 },
  { id: "Magento_Backend::marketing", label: "Marketing", level: 0 },
  { id: "Magento_CatalogRule::promo", label: "Promotions", level: 1 },
  { id: "Magento_CatalogRule::promo_catalog", label: "Catalog Price Rule", level: 2 },
  { id: "Magento_SalesRule::quote", label: "Cart Price Rules", level: 2 },
  { id: "Magento_Backend::marketing_communications", label: "Communications", level: 1 },
  { id: "Magento_Email::template", label: "Email Templates", level: 2 },
  { id: "Magento_Newsletter::template", label: "Newsletter Template", level: 2 },
  { id: "Magento_Newsletter::queue", label: "Newsletter Queue", level: 2 },
  { id: "Magento_Newsletter::subscriber", label: "Newsletter Subscribers", level: 2 },
  { id: "Magento_Backend::marketing_seo", label: "SEO & Search", level: 1 },
  { id: "Magento_Search::search", label: "Search Terms", level: 2 },
  { id: "Magento_Search::synonyms", label: "Search Synonyms", level: 2 },
  { id: "Magento_UrlRewrite::urlrewrite", label: "URL Rewrites", level: 2 },
  { id: "Magento_Sitemap::sitemap", label: "Site Map", level: 2 },
  { id: "Magento_Backend::marketing_user_content", label: "User Content", level: 1 },
  { id: "Magento_Review::reviews_all", label: "All Reviews", level: 2 },
  { id: "Magento_Review::pending", label: "Pending Reviews", level: 2 },
  { id: "Magento_Backend::content", label: "Content", level: 0 },
  { id: "Magento_Backend::content_elements", label: "Elements", level: 1 },
  { id: "Magento_Cms::page", label: "Pages", level: 2 },
  { id: "Magento_Cms::save", label: "Save Page", level: 3 },
  { id: "Magento_Cms::save_design", label: "Edit Page Design", level: 4 },
  { id: "Magento_Cms::page_delete", label: "Delete Page", level: 3 },
  { id: "Magento_Cms::block", label: "Blocks", level: 2 },
  { id: "Magento_Widget::widget_instance", label: "Widgets", level: 2 },
  { id: "Magento_Cms::media_gallery", label: "Media Gallery", level: 2 },
  { id: "Magento_MediaGalleryUiApi::insert_assets", label: "Insert assets into the content", level: 3 },
  { id: "Magento_MediaGalleryUiApi::upload_assets", label: "Upload assets", level: 3 },
  { id: "Magento_MediaGalleryUiApi::edit_assets", label: "Edit asset details", level: 3 },
  { id: "Magento_AdobeStockImageAdminUi::media_gallery", label: "Adobe Stock", level: 3 },
  { id: "Magento_AdobeStockImageAdminUi::save_preview_images", label: "Save Preview Image", level: 4 },
  { id: "Magento_AdobeStockImageAdminUi::license_images", label: "License images", level: 4 },
  { id: "Magento_MediaGalleryUiApi::delete_assets", label: "Delete assets", level: 3 },
  { id: "Magento_MediaGalleryUiApi::create_folder", label: "Create folder", level: 3 },
  { id: "Magento_MediaGalleryUiApi::delete_folder", label: "Delete folder", level: 3 },
  { id: "Magento_PageBuilder::templates", label: "Templates", level: 2 },
  { id: "Magento_PageBuilder::template_save", label: "Save Template", level: 3 },
  { id: "Magento_PageBuilder::template_apply", label: "Apply Template", level: 3 },
  { id: "Magento_PageBuilder::template_delete", label: "Delete Template", level: 3 },
  { id: "Magento_Backend::design", label: "Design", level: 1 },
  { id: "Magento_Theme::theme", label: "Themes", level: 2 },
  { id: "Magento_Backend::schedule", label: "Schedule", level: 2 },
  { id: "Magento_Backend::content_translation", label: "Content translation", level: 1 },
  { id: "Magento_Reports::report", label: "Reports", level: 0 },
  { id: "Magento_Reports::report_marketing", label: "Marketing", level: 1 },
  { id: "Magento_Reports::shopcart", label: "Shopping Cart", level: 2 },
  { id: "Magento_Reports::product", label: "Products in Cart", level: 3 },
  { id: "Magento_Reports::abandoned", label: "Abandoned Cart", level: 3 },
  { id: "Magento_Reports::report_search", label: "Search Terms", level: 2 },
  { id: "Magento_Newsletter::problem", label: "Newsletter Problem Reports", level: 2 },
  { id: "Magento_Reports::review", label: "Reviews", level: 1 },
  { id: "Magento_Reports::review_customer", label: "By Customers", level: 2 },
  { id: "Magento_Reports::review_product", label: "By Products", level: 2 },
  { id: "Magento_Reports::salesroot", label: "Sales", level: 1 },
  { id: "Magento_Reports::salesroot_sales", label: "Orders", level: 2 },
  { id: "Magento_Reports::tax", label: "Tax", level: 2 },
  { id: "Magento_Reports::invoiced", label: "Invoiced", level: 2 },
  { id: "Magento_Reports::shipping", label: "Shipping", level: 2 },
  { id: "Magento_Reports::refunded", label: "Refunds", level: 2 },
  { id: "Magento_Reports::coupons", label: "Coupons", level: 2 },
  { id: "Magento_Paypal::paypal_settlement_reports", label: "PayPal Settlement", level: 2 },
  { id: "Magento_Paypal::paypal_settlement_reports_view", label: "View", level: 3 },
  { id: "Magento_Paypal::fetch", label: "Fetch", level: 3 },
  { id: "PayPal_Braintree::settlement_report", label: "Braintree Settlement", level: 2 },
  { id: "Magento_Reports::customers", label: "Customers", level: 1 },
  { id: "Magento_Reports::totals", label: "Order Total", level: 2 },
  { id: "Magento_Reports::customers_orders", label: "Order Count", level: 2 },
  { id: "Magento_Reports::accounts", label: "New", level: 2 },
  { id: "Magento_Reports::report_products", label: "Products", level: 1 },
  { id: "Magento_Reports::viewed", label: "Views", level: 2 },
  { id: "Magento_Reports::bestsellers", label: "Bestsellers", level: 2 },
  { id: "Magento_Reports::lowstock", label: "Low Stock", level: 2 },
  { id: "Magento_Reports::sold", label: "Ordered", level: 2 },
  { id: "Magento_Reports::downloads", label: "Downloads", level: 2 },
  { id: "Magento_Reports::statistics", label: "Statistics", level: 1 },
  { id: "Magento_Reports::statistics_refresh", label: "Refresh Statistics", level: 2 },
  { id: "Magento_Analytics::business_intelligence", label: "Business Intelligence", level: 1 },
  { id: "Magento_Analytics::advanced_reporting", label: "Advanced Reporting", level: 2 },
  { id: "Magento_Analytics::bi_essentials", label: "BI Essentials", level: 2 },
  { id: "Magento_Backend::stores", label: "Stores", level: 0 },
  { id: "Magento_Backend::stores_settings", label: "Settings", level: 1 },
  { id: "Magento_Backend::store", label: "All Stores", level: 2 },
  { id: "Magento_Config::config", label: "Configuration", level: 2 },
  { id: "Magento_Cms::config_cms", label: "Content Management", level: 3 },
  { id: "Magento_Catalog::config_catalog", label: "Catalog Section", level: 3 },
  { id: "Magento_CatalogSearch::config_catalog_search", label: "Catalog Search", level: 4 },
  { id: "Magento_CatalogInventory::cataloginventory", label: "Inventory Section", level: 3 },
  { id: "Magento_Payment::payment", label: "Payment Methods Section", level: 3 },
  { id: "Magento_Payment::payment_services", label: "Payment Services", level: 3 },
  { id: "Magento_Downloadable::downloadable", label: "Downloadable Product Section", level: 3 },
  { id: "Magento_Contact::contact", label: "Contacts Section", level: 3 },
  { id: "Magento_GoogleAnalytics::google", label: "Google API", level: 3 },
  { id: "Magento_LoginAsCustomer::config_section", label: "Login as Customer Section", level: 3 },
  { id: "Magento_Newsletter::newsletter", label: "Newsletter Section", level: 3 },
  { id: "Magento_Shipping::carriers", label: "Delivery Methods Section", level: 3 },
  { id: "Magento_InventoryInStorePickupApi::inStorePickup", label: "In-Store Pickup", level: 4 },
  { id: "Magento_InventoryInStorePickupApi::notify_orders_are_ready_for_pickup", label: "Notify Orders Are Ready For Pickup", level: 5 },
  { id: "Magento_Shipping::config_shipping", label: "Shipping Settings Section", level: 3 },
  { id: "Magento_Shipping::shipping_policy", label: "Shipping Policy Parameters Section", level: 3 },
  { id: "Magento_Multishipping::config_multishipping", label: "Multishipping Settings Section", level: 3 },
  { id: "Magento_ReCaptchaUi::config", label: "reCAPTCHA", level: 3 },
  { id: "Magento_Securitytxt::config", label: "Securitytxt", level: 3 },
  { id: "Magento_Config::config_general", label: "General Section", level: 3 },
  { id: "Magento_Integration::config_oauth", label: "OAuth Configuration", level: 3 },
  { id: "Magento_Webapi::config_webapi", label: "Magento Web API", level: 3 },
  { id: "Magento_Config::web", label: "Web Section", level: 3 },
  { id: "Magento_Config::config_design", label: "Design Section", level: 3 },
  { id: "Magento_Customer::config_customer", label: "Customers Section", level: 3 },
  { id: "Magento_Paypal::paypal", label: "PayPal Section", level: 3 },
  { id: "Magento_Tax::config_tax", label: "Tax Section", level: 3 },
  { id: "Magento_Checkout::checkout", label: "Checkout Section", level: 3 },
  { id: "Magento_Sales::config_sales", label: "Sales Section", level: 3 },
  { id: "Magento_Persistent::persistent", label: "Persistent Shopping Cart", level: 3 },
  { id: "Magento_Sales::sales_email", label: "Sales Emails Section", level: 3 },
  { id: "Magento_Sales::sales_pdf", label: "PDF Print-outs", level: 3 },
  { id: "Magento_Reports::reports", label: "Reports", level: 3 },
  { id: "Magento_Sitemap::config_sitemap", label: "XML Sitemap Section", level: 3 },
  { id: "Magento_Config::config_system", label: "System Section", level: 3 },
  { id: "Magento_Wishlist::config_wishlist", label: "Wish List Section", level: 3 },
  { id: "Magento_SalesRule::config_promo", label: "Promotion", level: 3 },
  { id: "Magento_Config::config_admin", label: "Advanced Admin Section", level: 3 },
  { id: "Magento_Config::trans_email", label: "Store Email Addresses Section", level: 3 },
  { id: "Magento_Config::dev", label: "Developer Section", level: 3 },
  { id: "Magento_Config::currency", label: "Currency Setup Section", level: 3 },
  { id: "Magento_Rss::rss", label: "RSS Feeds Section", level: 3 },
  { id: "Magento_Config::sendfriend", label: "Email to a Friend", level: 3 },
  { id: "Magento_Analytics::analytics_settings", label: "Analytics", level: 3 },
  { id: "Magento_NewRelicReporting::config_newrelicreporting", label: "New Relic Reporting Section", level: 3 },
  { id: "Magento_CheckoutAgreements::checkoutagreement", label: "Terms & Conditions", level: 2 },
  { id: "Magento_Sales::order_statuses", label: "Order Status", level: 2 },
  { id: "Magento_InventoryApi::inventory", label: "Inventory", level: 1 },
  { id: "Magento_InventoryApi::source", label: "Sources", level: 2 },
  { id: "Magento_InventoryApi::source_edit", label: "Edit Sources", level: 3 },
  { id: "Magento_InventoryApi::ship_source_selection", label: "Shipping Source Selection", level: 3 },
  { id: "Magento_InventorySourceSelectionApi::source_selection_algorithm", label: "Inventory Source Selection", level: 3 },
  { id: "Magento_InventorySourceSelectionApi::source_selection_algorithm_post", label: "Source selection algorithm result", level: 4 },
  { id: "Magento_InventoryApi::stock", label: "Stocks", level: 2 },
  { id: "Magento_InventoryApi::stock_edit", label: "Edit Stocks", level: 3 },
  { id: "Magento_InventoryApi::stock_delete", label: "Delete Stocks", level: 3 },
  { id: "Magento_InventoryLowQuantityNotificationApi::low_quantity_notification", label: "Low Quantity Notification", level: 3 },
  { id: "Magento_InventoryLowQuantityNotificationApi::stock_create_low_quantity_notification", label: "Create low quantity notification", level: 4 },
  { id: "Magento_InventoryLowQuantityNotificationApi::stock_delete_low_quantity_notification", label: "Remove low quantity notification", level: 4 },
  { id: "Magento_InventoryApi::stock_source_link", label: "Source to Stock Assigning", level: 3 },
  { id: "Magento_InventoryApi::stock_source_item_assign", label: "Source Item Assigning", level: 3 },
  { id: "Magento_InventorySalesApi::stock", label: "Sales Stock", level: 2 },
  { id: "Magento_Tax::manage_tax", label: "Taxes", level: 1 },
  { id: "Magento_CurrencySymbol::system_currency", label: "Currency", level: 1 },
  { id: "Magento_CurrencySymbol::currency_rates", label: "Currency Rates", level: 2 },
  { id: "Magento_CurrencySymbol::symbols", label: "Currency Symbols", level: 2 },
  { id: "Magento_Backend::stores_attributes", label: "Attributes", level: 1 },
  { id: "Magento_Catalog::attributes_attributes", label: "Product", level: 2 },
  { id: "Magento_Catalog::sets", label: "Attribute Set", level: 2 },
  { id: "Magento_Review::ratings", label: "Ratings", level: 2 },
  { id: "Magento_Swatches::iframe", label: "Swatches", level: 2 },
  { id: "Magento_Backend::stores_other_settings", label: "Other Settings", level: 1 },
  { id: "Magento_Backend::system", label: "System", level: 0 },
  { id: "Magento_AdobeIms::adobe_ims", label: "Adobe IMS", level: 1 },
  { id: "Magento_AdobeIms::actions", label: "Actions", level: 2 },
  { id: "Magento_AdobeIms::login", label: "Login", level: 3 },
  { id: "Magento_AdobeIms::logout", label: "Logout", level: 3 },
  { id: "Magento_AdobeStockAsset::adobe_stock_asset", label: "Adobe Stock WebAPI", level: 1 },
  { id: "Magento_AdobeStockAsset::actions", label: "WebAPI Actions", level: 2 },
  { id: "Magento_AdobeStockAsset::actions_delete", label: "Delete", level: 3 },
  { id: "Magento_AdobeStockAsset::actions_save", label: "Save", level: 3 },
  { id: "Magento_AdobeStockAsset::actions_view", label: "View", level: 3 },
  { id: "Magento_AdobeStockAsset::actions_get", label: "Get", level: 3 },
  { id: "Magento_Backend::convert", label: "Data Transfer", level: 1 },
  { id: "Magento_ImportExport::import", label: "Import", level: 2 },
  { id: "Magento_ImportExport::export", label: "Export", level: 2 },
  { id: "Magento_TaxImportExport::import_export", label: "Import/Export Tax Rates", level: 2 },
  { id: "Magento_ImportExport::history", label: "Import History", level: 2 },
  { id: "Magento_Backend::extensions", label: "Magento Connect", level: 1 },
  { id: "Magento_Backend::local", label: "Connect Manager", level: 2 },
  { id: "Magento_Backend::custom", label: "Package Extensions", level: 2 },
  { id: "Magento_Integration::extensions", label: "System Extensions", level: 1 },
  { id: "Magento_Integration::integrations", label: "System Integrations", level: 2 },
  { id: "Magento_Backend::tools", label: "Tools", level: 1 },
  { id: "Magento_Backend::cache", label: "Cache Management", level: 2 },
  { id: "Magento_Backend::main_actions", label: "Clean Cache Actions", level: 3 },
  { id: "Magento_Backend::flush_cache_storage", label: "Flush Cache Storage", level: 4 },
  { id: "Magento_Backend::flush_magento_cache", label: "Flush Magento Cache", level: 4 },
  { id: "Magento_Backend::mass_actions", label: "Cache Types Management", level: 3 },
  { id: "Magento_Backend::toggling_cache_type", label: "Toggle Cache Type", level: 4 },
  { id: "Magento_Backend::refresh_cache_type", label: "Refresh Cache Type", level: 4 },
  { id: "Magento_Backend::additional_cache_management", label: "Additional Cache Management", level: 3 },
  { id: "Magento_Backend::flush_catalog_images", label: "Catalog Images Cache", level: 4 },
  { id: "Magento_Backend::flush_js_css", label: "Flush Js/Css", level: 4 },
  { id: "Magento_Backend::flush_static_files", label: "Flush Static Files", level: 4 },
  { id: "Magento_Backup::backup", label: "Backups", level: 2 },
  { id: "Magento_Backup::rollback", label: "Rollback", level: 3 },
  { id: "Magento_Indexer::index", label: "Index Management", level: 2 },
  { id: "Magento_Indexer::changeMode", label: "Change indexer mode", level: 2 },
  { id: "Magento_Indexer::invalidate", label: "Invalidate index", level: 2 },
  { id: "Magento_User::acl", label: "Permissions", level: 1 },
  { id: "Magento_User::acl_users", label: "All Users", level: 2 },
  { id: "Magento_User::locks", label: "Locked Users", level: 2 },
  { id: "Magento_User::acl_roles", label: "User Roles", level: 2 },
  { id: "Magento_Logging::magento_logging", label: "Action Log", level: 1 },
  { id: "Magento_Logging::magento_logging_events", label: "Report", level: 2 },
  { id: "Magento_Logging::system_magento_logging_bulk_operations", label: "Bulk Actions", level: 2 },
  { id: "Magento_Backend::system_other_settings", label: "Other Settings", level: 1 },
  { id: "Magento_AdminNotification::adminnotification", label: "Notifications", level: 2 },
  { id: "Magento_AdminNotification::show_toolbar", label: "Show Toolbar", level: 3 },
  { id: "Magento_AdminNotification::show_list", label: "Show List", level: 3 },
  { id: "Magento_AdminNotification::mark_as_read", label: "Mark as Read", level: 3 },
  { id: "Magento_AdminNotification::adminnotification_remove", label: "Remove", level: 3 },
  { id: "Magento_Variable::variable", label: "Custom Variables", level: 2 },
  { id: "Magento_EncryptionKey::crypt_key", label: "Manage Encryption Key", level: 2 },
  { id: "Magento_Backend::global_search", label: "Global Search", level: 0 },
]

/** Every resource id — what `Resource Access: All` grants. */
export const ALL_ACL_IDS = ACL_RESOURCES.map(r => r.id)
