/* Source-extracted option vocabularies for Stores > Configuration.
 *
 * DOM-201 — the mock had truncated these selects to 1-3 entries, which makes
 * "set the store timezone to X" unachievable for every X but one. Each list
 * below is the live source's own `<option>` set, in the source's order, pulled
 * verbatim out of the rendered
 * `/admin/admin/system_config/edit/section/general/` DOM.
 */

/** 416 entries — `groups[locale][fields][timezone][value]`. */
export const TIMEZONE_OPTIONS = [
  { value: "America/Eirunepe", label: "Acre Standard Time (America/Eirunepe)" },
  { value: "America/Rio_Branco", label: "Acre Standard Time (America/Rio_Branco)" },
  { value: "Asia/Kabul", label: "Afghanistan Time (Asia/Kabul)" },
  { value: "America/Anchorage", label: "Alaska Standard Time (America/Anchorage)" },
  { value: "America/Juneau", label: "Alaska Standard Time (America/Juneau)" },
  { value: "America/Metlakatla", label: "Alaska Standard Time (America/Metlakatla)" },
  { value: "America/Nome", label: "Alaska Standard Time (America/Nome)" },
  { value: "America/Sitka", label: "Alaska Standard Time (America/Sitka)" },
  { value: "America/Yakutat", label: "Alaska Standard Time (America/Yakutat)" },
  { value: "America/Boa_Vista", label: "Amazon Standard Time (America/Boa_Vista)" },
  { value: "America/Campo_Grande", label: "Amazon Standard Time (America/Campo_Grande)" },
  { value: "America/Cuiaba", label: "Amazon Standard Time (America/Cuiaba)" },
  { value: "America/Manaus", label: "Amazon Standard Time (America/Manaus)" },
  { value: "America/Porto_Velho", label: "Amazon Standard Time (America/Porto_Velho)" },
  { value: "Asia/Anadyr", label: "Anadyr Standard Time (Asia/Anadyr)" },
  { value: "Pacific/Apia", label: "Apia Standard Time (Pacific/Apia)" },
  { value: "Asia/Aden", label: "Arabian Standard Time (Asia/Aden)" },
  { value: "Asia/Baghdad", label: "Arabian Standard Time (Asia/Baghdad)" },
  { value: "Asia/Bahrain", label: "Arabian Standard Time (Asia/Bahrain)" },
  { value: "Asia/Kuwait", label: "Arabian Standard Time (Asia/Kuwait)" },
  { value: "Asia/Qatar", label: "Arabian Standard Time (Asia/Qatar)" },
  { value: "Asia/Riyadh", label: "Arabian Standard Time (Asia/Riyadh)" },
  { value: "America/Argentina/Buenos_Aires", label: "Argentina Standard Time (America/Argentina/Buenos_Aires)" },
  { value: "America/Argentina/Catamarca", label: "Argentina Standard Time (America/Argentina/Catamarca)" },
  { value: "America/Argentina/Cordoba", label: "Argentina Standard Time (America/Argentina/Cordoba)" },
  { value: "America/Argentina/Jujuy", label: "Argentina Standard Time (America/Argentina/Jujuy)" },
  { value: "America/Argentina/La_Rioja", label: "Argentina Standard Time (America/Argentina/La_Rioja)" },
  { value: "America/Argentina/Mendoza", label: "Argentina Standard Time (America/Argentina/Mendoza)" },
  { value: "America/Argentina/Rio_Gallegos", label: "Argentina Standard Time (America/Argentina/Rio_Gallegos)" },
  { value: "America/Argentina/Salta", label: "Argentina Standard Time (America/Argentina/Salta)" },
  { value: "America/Argentina/San_Juan", label: "Argentina Standard Time (America/Argentina/San_Juan)" },
  { value: "America/Argentina/San_Luis", label: "Argentina Standard Time (America/Argentina/San_Luis)" },
  { value: "America/Argentina/Tucuman", label: "Argentina Standard Time (America/Argentina/Tucuman)" },
  { value: "America/Argentina/Ushuaia", label: "Argentina Standard Time (America/Argentina/Ushuaia)" },
  { value: "Asia/Yerevan", label: "Armenia Standard Time (Asia/Yerevan)" },
  { value: "America/Anguilla", label: "Atlantic Standard Time (America/Anguilla)" },
  { value: "America/Antigua", label: "Atlantic Standard Time (America/Antigua)" },
  { value: "America/Aruba", label: "Atlantic Standard Time (America/Aruba)" },
  { value: "America/Barbados", label: "Atlantic Standard Time (America/Barbados)" },
  { value: "America/Blanc-Sablon", label: "Atlantic Standard Time (America/Blanc-Sablon)" },
  { value: "America/Curacao", label: "Atlantic Standard Time (America/Curacao)" },
  { value: "America/Dominica", label: "Atlantic Standard Time (America/Dominica)" },
  { value: "America/Glace_Bay", label: "Atlantic Standard Time (America/Glace_Bay)" },
  { value: "America/Goose_Bay", label: "Atlantic Standard Time (America/Goose_Bay)" },
  { value: "America/Grenada", label: "Atlantic Standard Time (America/Grenada)" },
  { value: "America/Guadeloupe", label: "Atlantic Standard Time (America/Guadeloupe)" },
  { value: "America/Halifax", label: "Atlantic Standard Time (America/Halifax)" },
  { value: "America/Kralendijk", label: "Atlantic Standard Time (America/Kralendijk)" },
  { value: "America/Lower_Princes", label: "Atlantic Standard Time (America/Lower_Princes)" },
  { value: "America/Marigot", label: "Atlantic Standard Time (America/Marigot)" },
  { value: "America/Martinique", label: "Atlantic Standard Time (America/Martinique)" },
  { value: "America/Moncton", label: "Atlantic Standard Time (America/Moncton)" },
  { value: "America/Montserrat", label: "Atlantic Standard Time (America/Montserrat)" },
  { value: "America/Port_of_Spain", label: "Atlantic Standard Time (America/Port_of_Spain)" },
  { value: "America/Puerto_Rico", label: "Atlantic Standard Time (America/Puerto_Rico)" },
  { value: "America/Santo_Domingo", label: "Atlantic Standard Time (America/Santo_Domingo)" },
  { value: "America/St_Barthelemy", label: "Atlantic Standard Time (America/St_Barthelemy)" },
  { value: "America/St_Kitts", label: "Atlantic Standard Time (America/St_Kitts)" },
  { value: "America/St_Lucia", label: "Atlantic Standard Time (America/St_Lucia)" },
  { value: "America/St_Thomas", label: "Atlantic Standard Time (America/St_Thomas)" },
  { value: "America/St_Vincent", label: "Atlantic Standard Time (America/St_Vincent)" },
  { value: "America/Thule", label: "Atlantic Standard Time (America/Thule)" },
  { value: "America/Tortola", label: "Atlantic Standard Time (America/Tortola)" },
  { value: "Atlantic/Bermuda", label: "Atlantic Standard Time (Atlantic/Bermuda)" },
  { value: "Australia/Adelaide", label: "Australian Central Standard Time (Australia/Adelaide)" },
  { value: "Australia/Broken_Hill", label: "Australian Central Standard Time (Australia/Broken_Hill)" },
  { value: "Australia/Darwin", label: "Australian Central Standard Time (Australia/Darwin)" },
  { value: "Australia/Eucla", label: "Australian Central Western Standard Time (Australia/Eucla)" },
  { value: "Antarctica/Macquarie", label: "Australian Eastern Standard Time (Antarctica/Macquarie)" },
  { value: "Australia/Brisbane", label: "Australian Eastern Standard Time (Australia/Brisbane)" },
  { value: "Australia/Hobart", label: "Australian Eastern Standard Time (Australia/Hobart)" },
  { value: "Australia/Lindeman", label: "Australian Eastern Standard Time (Australia/Lindeman)" },
  { value: "Australia/Melbourne", label: "Australian Eastern Standard Time (Australia/Melbourne)" },
  { value: "Australia/Sydney", label: "Australian Eastern Standard Time (Australia/Sydney)" },
  { value: "Australia/Perth", label: "Australian Western Standard Time (Australia/Perth)" },
  { value: "Asia/Baku", label: "Azerbaijan Standard Time (Asia/Baku)" },
  { value: "Atlantic/Azores", label: "Azores Standard Time (Atlantic/Azores)" },
  { value: "Asia/Dhaka", label: "Bangladesh Standard Time (Asia/Dhaka)" },
  { value: "Asia/Thimphu", label: "Bhutan Time (Asia/Thimphu)" },
  { value: "America/La_Paz", label: "Bolivia Time (America/La_Paz)" },
  { value: "America/Araguaina", label: "Brasilia Standard Time (America/Araguaina)" },
  { value: "America/Bahia", label: "Brasilia Standard Time (America/Bahia)" },
  { value: "America/Belem", label: "Brasilia Standard Time (America/Belem)" },
  { value: "America/Fortaleza", label: "Brasilia Standard Time (America/Fortaleza)" },
  { value: "America/Maceio", label: "Brasilia Standard Time (America/Maceio)" },
  { value: "America/Recife", label: "Brasilia Standard Time (America/Recife)" },
  { value: "America/Santarem", label: "Brasilia Standard Time (America/Santarem)" },
  { value: "America/Sao_Paulo", label: "Brasilia Standard Time (America/Sao_Paulo)" },
  { value: "Asia/Brunei", label: "Brunei Darussalam Time (Asia/Brunei)" },
  { value: "Atlantic/Cape_Verde", label: "Cape Verde Standard Time (Atlantic/Cape_Verde)" },
  { value: "Antarctica/Casey", label: "Casey Time (Antarctica/Casey)" },
  { value: "Africa/Blantyre", label: "Central Africa Time (Africa/Blantyre)" },
  { value: "Africa/Bujumbura", label: "Central Africa Time (Africa/Bujumbura)" },
  { value: "Africa/Gaborone", label: "Central Africa Time (Africa/Gaborone)" },
  { value: "Africa/Harare", label: "Central Africa Time (Africa/Harare)" },
  { value: "Africa/Juba", label: "Central Africa Time (Africa/Juba)" },
  { value: "Africa/Khartoum", label: "Central Africa Time (Africa/Khartoum)" },
  { value: "Africa/Kigali", label: "Central Africa Time (Africa/Kigali)" },
  { value: "Africa/Lubumbashi", label: "Central Africa Time (Africa/Lubumbashi)" },
  { value: "Africa/Lusaka", label: "Central Africa Time (Africa/Lusaka)" },
  { value: "Africa/Maputo", label: "Central Africa Time (Africa/Maputo)" },
  { value: "Africa/Windhoek", label: "Central Africa Time (Africa/Windhoek)" },
  { value: "Africa/Algiers", label: "Central European Standard Time (Africa/Algiers)" },
  { value: "Africa/Ceuta", label: "Central European Standard Time (Africa/Ceuta)" },
  { value: "Africa/Tunis", label: "Central European Standard Time (Africa/Tunis)" },
  { value: "Arctic/Longyearbyen", label: "Central European Standard Time (Arctic/Longyearbyen)" },
  { value: "Europe/Amsterdam", label: "Central European Standard Time (Europe/Amsterdam)" },
  { value: "Europe/Andorra", label: "Central European Standard Time (Europe/Andorra)" },
  { value: "Europe/Belgrade", label: "Central European Standard Time (Europe/Belgrade)" },
  { value: "Europe/Berlin", label: "Central European Standard Time (Europe/Berlin)" },
  { value: "Europe/Bratislava", label: "Central European Standard Time (Europe/Bratislava)" },
  { value: "Europe/Brussels", label: "Central European Standard Time (Europe/Brussels)" },
  { value: "Europe/Budapest", label: "Central European Standard Time (Europe/Budapest)" },
  { value: "Europe/Busingen", label: "Central European Standard Time (Europe/Busingen)" },
  { value: "Europe/Copenhagen", label: "Central European Standard Time (Europe/Copenhagen)" },
  { value: "Europe/Gibraltar", label: "Central European Standard Time (Europe/Gibraltar)" },
  { value: "Europe/Ljubljana", label: "Central European Standard Time (Europe/Ljubljana)" },
  { value: "Europe/Luxembourg", label: "Central European Standard Time (Europe/Luxembourg)" },
  { value: "Europe/Madrid", label: "Central European Standard Time (Europe/Madrid)" },
  { value: "Europe/Malta", label: "Central European Standard Time (Europe/Malta)" },
  { value: "Europe/Monaco", label: "Central European Standard Time (Europe/Monaco)" },
  { value: "Europe/Oslo", label: "Central European Standard Time (Europe/Oslo)" },
  { value: "Europe/Paris", label: "Central European Standard Time (Europe/Paris)" },
  { value: "Europe/Podgorica", label: "Central European Standard Time (Europe/Podgorica)" },
  { value: "Europe/Prague", label: "Central European Standard Time (Europe/Prague)" },
  { value: "Europe/Rome", label: "Central European Standard Time (Europe/Rome)" },
  { value: "Europe/San_Marino", label: "Central European Standard Time (Europe/San_Marino)" },
  { value: "Europe/Sarajevo", label: "Central European Standard Time (Europe/Sarajevo)" },
  { value: "Europe/Skopje", label: "Central European Standard Time (Europe/Skopje)" },
  { value: "Europe/Stockholm", label: "Central European Standard Time (Europe/Stockholm)" },
  { value: "Europe/Tirane", label: "Central European Standard Time (Europe/Tirane)" },
  { value: "Europe/Vaduz", label: "Central European Standard Time (Europe/Vaduz)" },
  { value: "Europe/Vatican", label: "Central European Standard Time (Europe/Vatican)" },
  { value: "Europe/Vienna", label: "Central European Standard Time (Europe/Vienna)" },
  { value: "Europe/Warsaw", label: "Central European Standard Time (Europe/Warsaw)" },
  { value: "Europe/Zagreb", label: "Central European Standard Time (Europe/Zagreb)" },
  { value: "Europe/Zurich", label: "Central European Standard Time (Europe/Zurich)" },
  { value: "Asia/Makassar", label: "Central Indonesia Time (Asia/Makassar)" },
  { value: "America/Bahia_Banderas", label: "Central Standard Time (America/Bahia_Banderas)" },
  { value: "America/Belize", label: "Central Standard Time (America/Belize)" },
  { value: "America/Chicago", label: "Central Standard Time (America/Chicago)" },
  { value: "America/Costa_Rica", label: "Central Standard Time (America/Costa_Rica)" },
  { value: "America/El_Salvador", label: "Central Standard Time (America/El_Salvador)" },
  { value: "America/Guatemala", label: "Central Standard Time (America/Guatemala)" },
  { value: "America/Indiana/Knox", label: "Central Standard Time (America/Indiana/Knox)" },
  { value: "America/Indiana/Tell_City", label: "Central Standard Time (America/Indiana/Tell_City)" },
  { value: "America/Managua", label: "Central Standard Time (America/Managua)" },
  { value: "America/Matamoros", label: "Central Standard Time (America/Matamoros)" },
  { value: "America/Menominee", label: "Central Standard Time (America/Menominee)" },
  { value: "America/Merida", label: "Central Standard Time (America/Merida)" },
  { value: "America/Mexico_City", label: "Central Standard Time (America/Mexico_City)" },
  { value: "America/Monterrey", label: "Central Standard Time (America/Monterrey)" },
  { value: "America/North_Dakota/Beulah", label: "Central Standard Time (America/North_Dakota/Beulah)" },
  { value: "America/North_Dakota/Center", label: "Central Standard Time (America/North_Dakota/Center)" },
  { value: "America/North_Dakota/New_Salem", label: "Central Standard Time (America/North_Dakota/New_Salem)" },
  { value: "America/Rankin_Inlet", label: "Central Standard Time (America/Rankin_Inlet)" },
  { value: "America/Regina", label: "Central Standard Time (America/Regina)" },
  { value: "America/Resolute", label: "Central Standard Time (America/Resolute)" },
  { value: "America/Swift_Current", label: "Central Standard Time (America/Swift_Current)" },
  { value: "America/Tegucigalpa", label: "Central Standard Time (America/Tegucigalpa)" },
  { value: "America/Winnipeg", label: "Central Standard Time (America/Winnipeg)" },
  { value: "Pacific/Guam", label: "Chamorro Standard Time (Pacific/Guam)" },
  { value: "Pacific/Saipan", label: "Chamorro Standard Time (Pacific/Saipan)" },
  { value: "Pacific/Chatham", label: "Chatham Standard Time (Pacific/Chatham)" },
  { value: "America/Santiago", label: "Chile Standard Time (America/Santiago)" },
  { value: "Asia/Macau", label: "China Standard Time (Asia/Macau)" },
  { value: "Asia/Shanghai", label: "China Standard Time (Asia/Shanghai)" },
  { value: "Indian/Christmas", label: "Christmas Island Time (Indian/Christmas)" },
  { value: "Pacific/Chuuk", label: "Chuuk Time (Pacific/Chuuk)" },
  { value: "Indian/Cocos", label: "Cocos Islands Time (Indian/Cocos)" },
  { value: "America/Bogota", label: "Colombia Standard Time (America/Bogota)" },
  { value: "Pacific/Rarotonga", label: "Cook Islands Standard Time (Pacific/Rarotonga)" },
  { value: "UTC", label: "Coordinated Universal Time (UTC)" },
  { value: "America/Havana", label: "Cuba Standard Time (America/Havana)" },
  { value: "Antarctica/Davis", label: "Davis Time (Antarctica/Davis)" },
  { value: "Antarctica/DumontDUrville", label: "Dumont-d\u2019Urville Time (Antarctica/DumontDUrville)" },
  { value: "Africa/Addis_Ababa", label: "East Africa Time (Africa/Addis_Ababa)" },
  { value: "Africa/Asmara", label: "East Africa Time (Africa/Asmara)" },
  { value: "Africa/Dar_es_Salaam", label: "East Africa Time (Africa/Dar_es_Salaam)" },
  { value: "Africa/Djibouti", label: "East Africa Time (Africa/Djibouti)" },
  { value: "Africa/Kampala", label: "East Africa Time (Africa/Kampala)" },
  { value: "Africa/Mogadishu", label: "East Africa Time (Africa/Mogadishu)" },
  { value: "Africa/Nairobi", label: "East Africa Time (Africa/Nairobi)" },
  { value: "Indian/Antananarivo", label: "East Africa Time (Indian/Antananarivo)" },
  { value: "Indian/Comoro", label: "East Africa Time (Indian/Comoro)" },
  { value: "Indian/Mayotte", label: "East Africa Time (Indian/Mayotte)" },
  { value: "America/Scoresbysund", label: "East Greenland Standard Time (America/Scoresbysund)" },
  { value: "Asia/Almaty", label: "East Kazakhstan Time (Asia/Almaty)" },
  { value: "Asia/Qostanay", label: "East Kazakhstan Time (Asia/Qostanay)" },
  { value: "Asia/Dili", label: "East Timor Time (Asia/Dili)" },
  { value: "Pacific/Easter", label: "Easter Island Standard Time (Pacific/Easter)" },
  { value: "Africa/Cairo", label: "Eastern European Standard Time (Africa/Cairo)" },
  { value: "Africa/Tripoli", label: "Eastern European Standard Time (Africa/Tripoli)" },
  { value: "Asia/Amman", label: "Eastern European Standard Time (Asia/Amman)" },
  { value: "Asia/Beirut", label: "Eastern European Standard Time (Asia/Beirut)" },
  { value: "Asia/Damascus", label: "Eastern European Standard Time (Asia/Damascus)" },
  { value: "Asia/Gaza", label: "Eastern European Standard Time (Asia/Gaza)" },
  { value: "Asia/Hebron", label: "Eastern European Standard Time (Asia/Hebron)" },
  { value: "Asia/Nicosia", label: "Eastern European Standard Time (Asia/Nicosia)" },
  { value: "Europe/Athens", label: "Eastern European Standard Time (Europe/Athens)" },
  { value: "Europe/Bucharest", label: "Eastern European Standard Time (Europe/Bucharest)" },
  { value: "Europe/Chisinau", label: "Eastern European Standard Time (Europe/Chisinau)" },
  { value: "Europe/Helsinki", label: "Eastern European Standard Time (Europe/Helsinki)" },
  { value: "Europe/Kaliningrad", label: "Eastern European Standard Time (Europe/Kaliningrad)" },
  { value: "Europe/Mariehamn", label: "Eastern European Standard Time (Europe/Mariehamn)" },
  { value: "Europe/Riga", label: "Eastern European Standard Time (Europe/Riga)" },
  { value: "Europe/Sofia", label: "Eastern European Standard Time (Europe/Sofia)" },
  { value: "Europe/Tallinn", label: "Eastern European Standard Time (Europe/Tallinn)" },
  { value: "Europe/Vilnius", label: "Eastern European Standard Time (Europe/Vilnius)" },
  { value: "Asia/Jayapura", label: "Eastern Indonesia Time (Asia/Jayapura)" },
  { value: "America/Atikokan", label: "Eastern Standard Time (America/Atikokan)" },
  { value: "America/Cancun", label: "Eastern Standard Time (America/Cancun)" },
  { value: "America/Cayman", label: "Eastern Standard Time (America/Cayman)" },
  { value: "America/Detroit", label: "Eastern Standard Time (America/Detroit)" },
  { value: "America/Grand_Turk", label: "Eastern Standard Time (America/Grand_Turk)" },
  { value: "America/Indiana/Indianapolis", label: "Eastern Standard Time (America/Indiana/Indianapolis)" },
  { value: "America/Indiana/Marengo", label: "Eastern Standard Time (America/Indiana/Marengo)" },
  { value: "America/Indiana/Petersburg", label: "Eastern Standard Time (America/Indiana/Petersburg)" },
  { value: "America/Indiana/Vevay", label: "Eastern Standard Time (America/Indiana/Vevay)" },
  { value: "America/Indiana/Vincennes", label: "Eastern Standard Time (America/Indiana/Vincennes)" },
  { value: "America/Indiana/Winamac", label: "Eastern Standard Time (America/Indiana/Winamac)" },
  { value: "America/Iqaluit", label: "Eastern Standard Time (America/Iqaluit)" },
  { value: "America/Jamaica", label: "Eastern Standard Time (America/Jamaica)" },
  { value: "America/Kentucky/Louisville", label: "Eastern Standard Time (America/Kentucky/Louisville)" },
  { value: "America/Kentucky/Monticello", label: "Eastern Standard Time (America/Kentucky/Monticello)" },
  { value: "America/Nassau", label: "Eastern Standard Time (America/Nassau)" },
  { value: "America/New_York", label: "Eastern Standard Time (America/New_York)" },
  { value: "America/Panama", label: "Eastern Standard Time (America/Panama)" },
  { value: "America/Port-au-Prince", label: "Eastern Standard Time (America/Port-au-Prince)" },
  { value: "America/Toronto", label: "Eastern Standard Time (America/Toronto)" },
  { value: "America/Guayaquil", label: "Ecuador Time (America/Guayaquil)" },
  { value: "Atlantic/Stanley", label: "Falkland Islands Standard Time (Atlantic/Stanley)" },
  { value: "America/Noronha", label: "Fernando de Noronha Standard Time (America/Noronha)" },
  { value: "Pacific/Fiji", label: "Fiji Standard Time (Pacific/Fiji)" },
  { value: "America/Cayenne", label: "French Guiana Time (America/Cayenne)" },
  { value: "Indian/Kerguelen", label: "French Southern & Antarctic Time (Indian/Kerguelen)" },
  { value: "America/Ciudad_Juarez", label: "GMT (America/Ciudad_Juarez)" },
  { value: "Europe/Kyiv", label: "GMT (Europe/Kyiv)" },
  { value: "Africa/Casablanca", label: "GMT+01:00 (Africa/Casablanca)" },
  { value: "Africa/El_Aaiun", label: "GMT+01:00 (Africa/El_Aaiun)" },
  { value: "Asia/Famagusta", label: "GMT+02:00 (Asia/Famagusta)" },
  { value: "Europe/Istanbul", label: "GMT+03:00 (Europe/Istanbul)" },
  { value: "Europe/Kirov", label: "GMT+03:00 (Europe/Kirov)" },
  { value: "Europe/Astrakhan", label: "GMT+04:00 (Europe/Astrakhan)" },
  { value: "Europe/Saratov", label: "GMT+04:00 (Europe/Saratov)" },
  { value: "Europe/Ulyanovsk", label: "GMT+04:00 (Europe/Ulyanovsk)" },
  { value: "Asia/Urumqi", label: "GMT+06:00 (Asia/Urumqi)" },
  { value: "Asia/Barnaul", label: "GMT+07:00 (Asia/Barnaul)" },
  { value: "Asia/Tomsk", label: "GMT+07:00 (Asia/Tomsk)" },
  { value: "America/Punta_Arenas", label: "GMT-03:00 (America/Punta_Arenas)" },
  { value: "Antarctica/Palmer", label: "GMT-03:00 (Antarctica/Palmer)" },
  { value: "Pacific/Galapagos", label: "Galapagos Time (Pacific/Galapagos)" },
  { value: "Pacific/Gambier", label: "Gambier Time (Pacific/Gambier)" },
  { value: "Asia/Tbilisi", label: "Georgia Standard Time (Asia/Tbilisi)" },
  { value: "Pacific/Tarawa", label: "Gilbert Islands Time (Pacific/Tarawa)" },
  { value: "Africa/Abidjan", label: "Greenwich Mean Time (Africa/Abidjan)" },
  { value: "Africa/Accra", label: "Greenwich Mean Time (Africa/Accra)" },
  { value: "Africa/Bamako", label: "Greenwich Mean Time (Africa/Bamako)" },
  { value: "Africa/Banjul", label: "Greenwich Mean Time (Africa/Banjul)" },
  { value: "Africa/Bissau", label: "Greenwich Mean Time (Africa/Bissau)" },
  { value: "Africa/Conakry", label: "Greenwich Mean Time (Africa/Conakry)" },
  { value: "Africa/Dakar", label: "Greenwich Mean Time (Africa/Dakar)" },
  { value: "Africa/Freetown", label: "Greenwich Mean Time (Africa/Freetown)" },
  { value: "Africa/Lome", label: "Greenwich Mean Time (Africa/Lome)" },
  { value: "Africa/Monrovia", label: "Greenwich Mean Time (Africa/Monrovia)" },
  { value: "Africa/Nouakchott", label: "Greenwich Mean Time (Africa/Nouakchott)" },
  { value: "Africa/Ouagadougou", label: "Greenwich Mean Time (Africa/Ouagadougou)" },
  { value: "Africa/Sao_Tome", label: "Greenwich Mean Time (Africa/Sao_Tome)" },
  { value: "America/Danmarkshavn", label: "Greenwich Mean Time (America/Danmarkshavn)" },
  { value: "Atlantic/Reykjavik", label: "Greenwich Mean Time (Atlantic/Reykjavik)" },
  { value: "Atlantic/St_Helena", label: "Greenwich Mean Time (Atlantic/St_Helena)" },
  { value: "Europe/Dublin", label: "Greenwich Mean Time (Europe/Dublin)" },
  { value: "Europe/Guernsey", label: "Greenwich Mean Time (Europe/Guernsey)" },
  { value: "Europe/Isle_of_Man", label: "Greenwich Mean Time (Europe/Isle_of_Man)" },
  { value: "Europe/Jersey", label: "Greenwich Mean Time (Europe/Jersey)" },
  { value: "Europe/London", label: "Greenwich Mean Time (Europe/London)" },
  { value: "Asia/Dubai", label: "Gulf Standard Time (Asia/Dubai)" },
  { value: "Asia/Muscat", label: "Gulf Standard Time (Asia/Muscat)" },
  { value: "America/Guyana", label: "Guyana Time (America/Guyana)" },
  { value: "America/Adak", label: "Hawaii-Aleutian Standard Time (America/Adak)" },
  { value: "Pacific/Honolulu", label: "Hawaii-Aleutian Standard Time (Pacific/Honolulu)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong Standard Time (Asia/Hong_Kong)" },
  { value: "Asia/Hovd", label: "Hovd Standard Time (Asia/Hovd)" },
  { value: "Asia/Colombo", label: "India Standard Time (Asia/Colombo)" },
  { value: "Asia/Kolkata", label: "India Standard Time (Asia/Kolkata)" },
  { value: "Indian/Chagos", label: "Indian Ocean Time (Indian/Chagos)" },
  { value: "Asia/Bangkok", label: "Indochina Time (Asia/Bangkok)" },
  { value: "Asia/Ho_Chi_Minh", label: "Indochina Time (Asia/Ho_Chi_Minh)" },
  { value: "Asia/Phnom_Penh", label: "Indochina Time (Asia/Phnom_Penh)" },
  { value: "Asia/Vientiane", label: "Indochina Time (Asia/Vientiane)" },
  { value: "Asia/Tehran", label: "Iran Standard Time (Asia/Tehran)" },
  { value: "Asia/Irkutsk", label: "Irkutsk Standard Time (Asia/Irkutsk)" },
  { value: "Asia/Jerusalem", label: "Israel Standard Time (Asia/Jerusalem)" },
  { value: "Asia/Tokyo", label: "Japan Standard Time (Asia/Tokyo)" },
  { value: "Asia/Pyongyang", label: "Korean Standard Time (Asia/Pyongyang)" },
  { value: "Asia/Seoul", label: "Korean Standard Time (Asia/Seoul)" },
  { value: "Pacific/Kosrae", label: "Kosrae Time (Pacific/Kosrae)" },
  { value: "Asia/Krasnoyarsk", label: "Krasnoyarsk Standard Time (Asia/Krasnoyarsk)" },
  { value: "Asia/Novokuznetsk", label: "Krasnoyarsk Standard Time (Asia/Novokuznetsk)" },
  { value: "Asia/Bishkek", label: "Kyrgyzstan Time (Asia/Bishkek)" },
  { value: "Pacific/Kiritimati", label: "Line Islands Time (Pacific/Kiritimati)" },
  { value: "Australia/Lord_Howe", label: "Lord Howe Standard Time (Australia/Lord_Howe)" },
  { value: "Asia/Magadan", label: "Magadan Standard Time (Asia/Magadan)" },
  { value: "Asia/Kuala_Lumpur", label: "Malaysia Time (Asia/Kuala_Lumpur)" },
  { value: "Asia/Kuching", label: "Malaysia Time (Asia/Kuching)" },
  { value: "Indian/Maldives", label: "Maldives Time (Indian/Maldives)" },
  { value: "Pacific/Marquesas", label: "Marquesas Time (Pacific/Marquesas)" },
  { value: "Pacific/Kwajalein", label: "Marshall Islands Time (Pacific/Kwajalein)" },
  { value: "Pacific/Majuro", label: "Marshall Islands Time (Pacific/Majuro)" },
  { value: "Indian/Mauritius", label: "Mauritius Standard Time (Indian/Mauritius)" },
  { value: "Antarctica/Mawson", label: "Mawson Time (Antarctica/Mawson)" },
  { value: "America/Chihuahua", label: "Mexican Pacific Standard Time (America/Chihuahua)" },
  { value: "America/Hermosillo", label: "Mexican Pacific Standard Time (America/Hermosillo)" },
  { value: "America/Mazatlan", label: "Mexican Pacific Standard Time (America/Mazatlan)" },
  { value: "Europe/Minsk", label: "Moscow Standard Time (Europe/Minsk)" },
  { value: "Europe/Moscow", label: "Moscow Standard Time (Europe/Moscow)" },
  { value: "Europe/Simferopol", label: "Moscow Standard Time (Europe/Simferopol)" },
  { value: "America/Boise", label: "Mountain Standard Time (America/Boise)" },
  { value: "America/Cambridge_Bay", label: "Mountain Standard Time (America/Cambridge_Bay)" },
  { value: "America/Creston", label: "Mountain Standard Time (America/Creston)" },
  { value: "America/Dawson_Creek", label: "Mountain Standard Time (America/Dawson_Creek)" },
  { value: "America/Denver", label: "Mountain Standard Time (America/Denver)" },
  { value: "America/Edmonton", label: "Mountain Standard Time (America/Edmonton)" },
  { value: "America/Fort_Nelson", label: "Mountain Standard Time (America/Fort_Nelson)" },
  { value: "America/Inuvik", label: "Mountain Standard Time (America/Inuvik)" },
  { value: "America/Ojinaga", label: "Mountain Standard Time (America/Ojinaga)" },
  { value: "America/Phoenix", label: "Mountain Standard Time (America/Phoenix)" },
  { value: "America/Yellowknife", label: "Mountain Standard Time (America/Yellowknife)" },
  { value: "Asia/Yangon", label: "Myanmar Time (Asia/Yangon)" },
  { value: "Pacific/Nauru", label: "Nauru Time (Pacific/Nauru)" },
  { value: "Asia/Kathmandu", label: "Nepal Time (Asia/Kathmandu)" },
  { value: "Pacific/Noumea", label: "New Caledonia Standard Time (Pacific/Noumea)" },
  { value: "Antarctica/McMurdo", label: "New Zealand Standard Time (Antarctica/McMurdo)" },
  { value: "Pacific/Auckland", label: "New Zealand Standard Time (Pacific/Auckland)" },
  { value: "America/St_Johns", label: "Newfoundland Standard Time (America/St_Johns)" },
  { value: "Pacific/Niue", label: "Niue Time (Pacific/Niue)" },
  { value: "Pacific/Norfolk", label: "Norfolk Island Standard Time (Pacific/Norfolk)" },
  { value: "Asia/Novosibirsk", label: "Novosibirsk Standard Time (Asia/Novosibirsk)" },
  { value: "Asia/Omsk", label: "Omsk Standard Time (Asia/Omsk)" },
  { value: "America/Los_Angeles", label: "Pacific Standard Time (America/Los_Angeles)" },
  { value: "America/Tijuana", label: "Pacific Standard Time (America/Tijuana)" },
  { value: "America/Vancouver", label: "Pacific Standard Time (America/Vancouver)" },
  { value: "Asia/Karachi", label: "Pakistan Standard Time (Asia/Karachi)" },
  { value: "Pacific/Palau", label: "Palau Time (Pacific/Palau)" },
  { value: "Pacific/Port_Moresby", label: "Papua New Guinea Time (Pacific/Port_Moresby)" },
  { value: "America/Asuncion", label: "Paraguay Standard Time (America/Asuncion)" },
  { value: "America/Lima", label: "Peru Standard Time (America/Lima)" },
  { value: "Asia/Kamchatka", label: "Petropavlovsk-Kamchatski Standard Time (Asia/Kamchatka)" },
  { value: "Asia/Manila", label: "Philippine Standard Time (Asia/Manila)" },
  { value: "Pacific/Kanton", label: "Phoenix Islands Time (Pacific/Kanton)" },
  { value: "Pacific/Pitcairn", label: "Pitcairn Time (Pacific/Pitcairn)" },
  { value: "Pacific/Pohnpei", label: "Ponape Time (Pacific/Pohnpei)" },
  { value: "Antarctica/Rothera", label: "Rothera Time (Antarctica/Rothera)" },
  { value: "Indian/Reunion", label: "R\u00e9union Time (Indian/Reunion)" },
  { value: "Asia/Sakhalin", label: "Sakhalin Standard Time (Asia/Sakhalin)" },
  { value: "Europe/Samara", label: "Samara Standard Time (Europe/Samara)" },
  { value: "Pacific/Midway", label: "Samoa Standard Time (Pacific/Midway)" },
  { value: "Pacific/Pago_Pago", label: "Samoa Standard Time (Pacific/Pago_Pago)" },
  { value: "Indian/Mahe", label: "Seychelles Time (Indian/Mahe)" },
  { value: "Asia/Singapore", label: "Singapore Standard Time (Asia/Singapore)" },
  { value: "Pacific/Guadalcanal", label: "Solomon Islands Time (Pacific/Guadalcanal)" },
  { value: "Africa/Johannesburg", label: "South Africa Standard Time (Africa/Johannesburg)" },
  { value: "Africa/Maseru", label: "South Africa Standard Time (Africa/Maseru)" },
  { value: "Africa/Mbabane", label: "South Africa Standard Time (Africa/Mbabane)" },
  { value: "Atlantic/South_Georgia", label: "South Georgia Time (Atlantic/South_Georgia)" },
  { value: "America/Miquelon", label: "St. Pierre & Miquelon Standard Time (America/Miquelon)" },
  { value: "America/Paramaribo", label: "Suriname Time (America/Paramaribo)" },
  { value: "Antarctica/Syowa", label: "Syowa Time (Antarctica/Syowa)" },
  { value: "Pacific/Tahiti", label: "Tahiti Time (Pacific/Tahiti)" },
  { value: "Asia/Taipei", label: "Taipei Standard Time (Asia/Taipei)" },
  { value: "Asia/Dushanbe", label: "Tajikistan Time (Asia/Dushanbe)" },
  { value: "Pacific/Fakaofo", label: "Tokelau Time (Pacific/Fakaofo)" },
  { value: "Pacific/Tongatapu", label: "Tonga Standard Time (Pacific/Tongatapu)" },
  { value: "Asia/Ashgabat", label: "Turkmenistan Standard Time (Asia/Ashgabat)" },
  { value: "Pacific/Funafuti", label: "Tuvalu Time (Pacific/Funafuti)" },
  { value: "Asia/Choibalsan", label: "Ulaanbaatar Standard Time (Asia/Choibalsan)" },
  { value: "Asia/Ulaanbaatar", label: "Ulaanbaatar Standard Time (Asia/Ulaanbaatar)" },
  { value: "America/Montevideo", label: "Uruguay Standard Time (America/Montevideo)" },
  { value: "Asia/Samarkand", label: "Uzbekistan Standard Time (Asia/Samarkand)" },
  { value: "Asia/Tashkent", label: "Uzbekistan Standard Time (Asia/Tashkent)" },
  { value: "Pacific/Efate", label: "Vanuatu Standard Time (Pacific/Efate)" },
  { value: "America/Caracas", label: "Venezuela Time (America/Caracas)" },
  { value: "Asia/Ust-Nera", label: "Vladivostok Standard Time (Asia/Ust-Nera)" },
  { value: "Asia/Vladivostok", label: "Vladivostok Standard Time (Asia/Vladivostok)" },
  { value: "Europe/Volgograd", label: "Volgograd Standard Time (Europe/Volgograd)" },
  { value: "Antarctica/Vostok", label: "Vostok Time (Antarctica/Vostok)" },
  { value: "Pacific/Wake", label: "Wake Island Time (Pacific/Wake)" },
  { value: "Pacific/Wallis", label: "Wallis & Futuna Time (Pacific/Wallis)" },
  { value: "Africa/Bangui", label: "West Africa Standard Time (Africa/Bangui)" },
  { value: "Africa/Brazzaville", label: "West Africa Standard Time (Africa/Brazzaville)" },
  { value: "Africa/Douala", label: "West Africa Standard Time (Africa/Douala)" },
  { value: "Africa/Kinshasa", label: "West Africa Standard Time (Africa/Kinshasa)" },
  { value: "Africa/Lagos", label: "West Africa Standard Time (Africa/Lagos)" },
  { value: "Africa/Libreville", label: "West Africa Standard Time (Africa/Libreville)" },
  { value: "Africa/Luanda", label: "West Africa Standard Time (Africa/Luanda)" },
  { value: "Africa/Malabo", label: "West Africa Standard Time (Africa/Malabo)" },
  { value: "Africa/Ndjamena", label: "West Africa Standard Time (Africa/Ndjamena)" },
  { value: "Africa/Niamey", label: "West Africa Standard Time (Africa/Niamey)" },
  { value: "Africa/Porto-Novo", label: "West Africa Standard Time (Africa/Porto-Novo)" },
  { value: "America/Nuuk", label: "West Greenland Standard Time (America/Nuuk)" },
  { value: "Asia/Aqtau", label: "West Kazakhstan Time (Asia/Aqtau)" },
  { value: "Asia/Aqtobe", label: "West Kazakhstan Time (Asia/Aqtobe)" },
  { value: "Asia/Atyrau", label: "West Kazakhstan Time (Asia/Atyrau)" },
  { value: "Asia/Oral", label: "West Kazakhstan Time (Asia/Oral)" },
  { value: "Asia/Qyzylorda", label: "West Kazakhstan Time (Asia/Qyzylorda)" },
  { value: "Atlantic/Canary", label: "Western European Standard Time (Atlantic/Canary)" },
  { value: "Atlantic/Faroe", label: "Western European Standard Time (Atlantic/Faroe)" },
  { value: "Atlantic/Madeira", label: "Western European Standard Time (Atlantic/Madeira)" },
  { value: "Europe/Lisbon", label: "Western European Standard Time (Europe/Lisbon)" },
  { value: "Asia/Jakarta", label: "Western Indonesia Time (Asia/Jakarta)" },
  { value: "Asia/Pontianak", label: "Western Indonesia Time (Asia/Pontianak)" },
  { value: "Asia/Khandyga", label: "Yakutsk Standard Time (Asia/Khandyga)" },
  { value: "Asia/Yakutsk", label: "Yakutsk Standard Time (Asia/Yakutsk)" },
  { value: "Asia/Yekaterinburg", label: "Yekaterinburg Standard Time (Asia/Yekaterinburg)" },
  { value: "America/Dawson", label: "Yukon Time (America/Dawson)" },
  { value: "America/Whitehorse", label: "Yukon Time (America/Whitehorse)" },
]

/** 249 entries incl. the leading `--Please Select--` — the country selects. */
export const CONFIG_COUNTRY_OPTIONS = [
  { value: "", label: "--Please Select--" },
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AS", label: "American Samoa" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AI", label: "Anguilla" },
  { value: "AQ", label: "Antarctica" },
  { value: "AG", label: "Antigua & Barbuda" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AW", label: "Aruba" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BS", label: "Bahamas" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BM", label: "Bermuda" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BA", label: "Bosnia & Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BV", label: "Bouvet Island" },
  { value: "BR", label: "Brazil" },
  { value: "IO", label: "British Indian Ocean Territory" },
  { value: "VG", label: "British Virgin Islands" },
  { value: "BN", label: "Brunei" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "CV", label: "Cape Verde" },
  { value: "BQ", label: "Caribbean Netherlands" },
  { value: "KY", label: "Cayman Islands" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CX", label: "Christmas Island" },
  { value: "CC", label: "Cocos (Keeling) Islands" },
  { value: "CO", label: "Colombia" },
  { value: "KM", label: "Comoros" },
  { value: "CG", label: "Congo - Brazzaville" },
  { value: "CD", label: "Congo - Kinshasa" },
  { value: "CK", label: "Cook Islands" },
  { value: "CR", label: "Costa Rica" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CW", label: "Cura\u00e7ao" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czechia" },
  { value: "CI", label: "C\u00f4te d\u2019Ivoire" },
  { value: "DK", label: "Denmark" },
  { value: "DJ", label: "Djibouti" },
  { value: "DM", label: "Dominica" },
  { value: "DO", label: "Dominican Republic" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "SZ", label: "Eswatini" },
  { value: "ET", label: "Ethiopia" },
  { value: "FK", label: "Falkland Islands" },
  { value: "FO", label: "Faroe Islands" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GF", label: "French Guiana" },
  { value: "PF", label: "French Polynesia" },
  { value: "TF", label: "French Southern Territories" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" },
  { value: "DE", label: "Germany" },
  { value: "GH", label: "Ghana" },
  { value: "GI", label: "Gibraltar" },
  { value: "GR", label: "Greece" },
  { value: "GL", label: "Greenland" },
  { value: "GD", label: "Grenada" },
  { value: "GP", label: "Guadeloupe" },
  { value: "GU", label: "Guam" },
  { value: "GT", label: "Guatemala" },
  { value: "GG", label: "Guernsey" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HM", label: "Heard & McDonald Islands" },
  { value: "HN", label: "Honduras" },
  { value: "HK", label: "Hong Kong SAR China" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Iran" },
  { value: "IQ", label: "Iraq" },
  { value: "IE", label: "Ireland" },
  { value: "IM", label: "Isle of Man" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japan" },
  { value: "JE", label: "Jersey" },
  { value: "JO", label: "Jordan" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "KE", label: "Kenya" },
  { value: "KI", label: "Kiribati" },
  { value: "XK", label: "Kosovo" },
  { value: "KW", label: "Kuwait" },
  { value: "KG", label: "Kyrgyzstan" },
  { value: "LA", label: "Laos" },
  { value: "LV", label: "Latvia" },
  { value: "LB", label: "Lebanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MO", label: "Macao SAR China" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "MV", label: "Maldives" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MH", label: "Marshall Islands" },
  { value: "MQ", label: "Martinique" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "YT", label: "Mayotte" },
  { value: "MX", label: "Mexico" },
  { value: "FM", label: "Micronesia" },
  { value: "MD", label: "Moldova" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolia" },
  { value: "ME", label: "Montenegro" },
  { value: "MS", label: "Montserrat" },
  { value: "MA", label: "Morocco" },
  { value: "MZ", label: "Mozambique" },
  { value: "MM", label: "Myanmar (Burma)" },
  { value: "NA", label: "Namibia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepal" },
  { value: "NL", label: "Netherlands" },
  { value: "NC", label: "New Caledonia" },
  { value: "NZ", label: "New Zealand" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "NU", label: "Niue" },
  { value: "NF", label: "Norfolk Island" },
  { value: "KP", label: "North Korea" },
  { value: "MK", label: "North Macedonia" },
  { value: "MP", label: "Northern Mariana Islands" },
  { value: "NO", label: "Norway" },
  { value: "OM", label: "Oman" },
  { value: "PK", label: "Pakistan" },
  { value: "PW", label: "Palau" },
  { value: "PS", label: "Palestinian Territories" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PN", label: "Pitcairn Islands" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "QA", label: "Qatar" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russia" },
  { value: "RW", label: "Rwanda" },
  { value: "RE", label: "R\u00e9union" },
  { value: "WS", label: "Samoa" },
  { value: "SM", label: "San Marino" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Singapore" },
  { value: "SX", label: "Sint Maarten" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "SB", label: "Solomon Islands" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "South Africa" },
  { value: "GS", label: "South Georgia & South Sandwich Islands" },
  { value: "KR", label: "South Korea" },
  { value: "ES", label: "Spain" },
  { value: "LK", label: "Sri Lanka" },
  { value: "BL", label: "St. Barth\u00e9lemy" },
  { value: "SH", label: "St. Helena" },
  { value: "KN", label: "St. Kitts & Nevis" },
  { value: "LC", label: "St. Lucia" },
  { value: "MF", label: "St. Martin" },
  { value: "PM", label: "St. Pierre & Miquelon" },
  { value: "VC", label: "St. Vincent & Grenadines" },
  { value: "SD", label: "Sudan" },
  { value: "SR", label: "Suriname" },
  { value: "SJ", label: "Svalbard & Jan Mayen" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "SY", label: "Syria" },
  { value: "ST", label: "S\u00e3o Tom\u00e9 & Pr\u00edncipe" },
  { value: "TW", label: "Taiwan, Province of China" },
  { value: "TJ", label: "Tajikistan" },
  { value: "TZ", label: "Tanzania" },
  { value: "TH", label: "Thailand" },
  { value: "TL", label: "Timor-Leste" },
  { value: "TG", label: "Togo" },
  { value: "TK", label: "Tokelau" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad & Tobago" },
  { value: "TN", label: "Tunisia" },
  { value: "TR", label: "Turkey" },
  { value: "TM", label: "Turkmenistan" },
  { value: "TC", label: "Turks & Caicos Islands" },
  { value: "TV", label: "Tuvalu" },
  { value: "UM", label: "U.S. Outlying Islands" },
  { value: "VI", label: "U.S. Virgin Islands" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "VU", label: "Vanuatu" },
  { value: "VA", label: "Vatican City" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Vietnam" },
  { value: "WF", label: "Wallis & Futuna" },
  { value: "EH", label: "Western Sahara" },
  { value: "YE", label: "Yemen" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
  { value: "AX", label: "\u00c5land Islands" },
]

/** `groups[locale][fields][code][value]`. */
export const LOCALE_OPTIONS = [
  { value: "en_GB", label: "English (United Kingdom)" },
  { value: "en_US", label: "English (United States)" },
]

/** `groups[locale][fields][firstday][value]`. */
export const FIRSTDAY_OPTIONS = [
  { value: "0", label: "Sunday" },
  { value: "1", label: "Monday" },
  { value: "2", label: "Tuesday" },
  { value: "3", label: "Wednesday" },
  { value: "4", label: "Thursday" },
  { value: "5", label: "Friday" },
  { value: "6", label: "Saturday" },
]

/** `…[fields][error_email_identity][value]` — 5 senders, not 3. */
export const EMAIL_IDENTITY_OPTIONS = [
  { value: 'general', label: 'General Contact' },
  { value: 'sales', label: 'Sales Representative' },
  { value: 'support', label: 'Customer Support' },
  { value: 'custom1', label: 'Custom Email 1' },
  { value: 'custom2', label: 'Custom Email 2' },
]

/* ---------------------------------------------------------------------------
 * F-01 / DOM-200 — the six `admin__control-multiselect` controls in
 * Stores > Configuration > General.
 *
 * The mock rendered these as `<input type="text">`, so
 * `[name="groups[country][fields][allow][value][]"]` — the name an evaluator
 * drives — resolved to nothing. The source emits
 * `<select name="…[value][]" multiple size="10">` plus a hidden `…[value]`
 * mirror, and (on the inherited ones) a hidden `…[value]_disabled`.
 * Option sets and default selections below are the live source's own, read off
 * the rendered `/admin/admin/system_config/edit/section/general/` DOM.
 * ------------------------------------------------------------------------- */

/** 248 — the country multiselects carry no `--Please Select--` row. */
export const CONFIG_COUNTRY_MULTI_OPTIONS = CONFIG_COUNTRY_OPTIONS.filter(o => o.value !== '')

/** `groups[locale][fields][weekend][value][]` — same 7 rows as First Day of Week. */
export const WEEKEND_OPTIONS = FIRSTDAY_OPTIONS

/** Selected sets as the source renders them (comma-joined, Magento's own storage form). */
export const COUNTRY_ALLOW_DEFAULT = CONFIG_COUNTRY_MULTI_OPTIONS.map(o => o.value).join(',')
export const COUNTRY_EU_DEFAULT = 'AT,BE,BG,HR,CY,CZ,DK,EE,FI,FR,DE,GR,HU,IE,IT,LV,LT,LU,MT,NL,PL,PT,RO,SK,SI,ES,SE'
export const COUNTRY_OPTIONAL_ZIP_DEFAULT = 'HK,IE,MO,PA,GB'
export const WEEKEND_DEFAULT = '0,6'
