/**
 * Stores > Configuration > Currency Setup option lists, captured verbatim off
 * the live source form (`/admin/admin/system_config/edit/section/currency/`,
 * read-only) this round.
 *
 * The mock shipped a two-entry `[USD, EUR]` list where the source offers all
 * 168 currencies Magento knows about (G-05). Trimming a real option list is the
 * defect this file exists to close: an agent told to set the base currency to
 * Japanese Yen could not have done it.
 */

export const CURRENCY_OPTIONS = [
  { value: "AFN", label: "Afghan Afghani" },
  { value: "ALL", label: "Albanian Lek" },
  { value: "DZD", label: "Algerian Dinar" },
  { value: "AOA", label: "Angolan Kwanza" },
  { value: "ARS", label: "Argentine Peso" },
  { value: "AMD", label: "Armenian Dram" },
  { value: "AWG", label: "Aruban Florin" },
  { value: "AUD", label: "Australian Dollar" },
  { value: "AZN", label: "Azerbaijani Manat" },
  { value: "AZM", label: "Azerbaijani Manat (1993\u20132006)" },
  { value: "BSD", label: "Bahamian Dollar" },
  { value: "BHD", label: "Bahraini Dinar" },
  { value: "BDT", label: "Bangladeshi Taka" },
  { value: "BBD", label: "Barbadian Dollar" },
  { value: "BYN", label: "Belarusian Ruble" },
  { value: "BZD", label: "Belize Dollar" },
  { value: "BMD", label: "Bermudan Dollar" },
  { value: "BTN", label: "Bhutanese Ngultrum" },
  { value: "BOB", label: "Bolivian Boliviano" },
  { value: "BAM", label: "Bosnia-Herzegovina Convertible Mark" },
  { value: "BWP", label: "Botswanan Pula" },
  { value: "BRL", label: "Brazilian Real" },
  { value: "GBP", label: "British Pound" },
  { value: "BND", label: "Brunei Dollar" },
  { value: "BGN", label: "Bulgarian Lev" },
  { value: "BUK", label: "Burmese Kyat" },
  { value: "BIF", label: "Burundian Franc" },
  { value: "XPF", label: "CFP Franc" },
  { value: "KHR", label: "Cambodian Riel" },
  { value: "CAD", label: "Canadian Dollar" },
  { value: "CVE", label: "Cape Verdean Escudo" },
  { value: "KYD", label: "Cayman Islands Dollar" },
  { value: "CLP", label: "Chilean Peso" },
  { value: "CNY", label: "Chinese Yuan" },
  { value: "COP", label: "Colombian Peso" },
  { value: "KMF", label: "Comorian Franc" },
  { value: "CDF", label: "Congolese Franc" },
  { value: "CRC", label: "Costa Rican Col\u00f3n" },
  { value: "HRK", label: "Croatian Kuna" },
  { value: "CUP", label: "Cuban Peso" },
  { value: "CZK", label: "Czech Koruna" },
  { value: "DKK", label: "Danish Krone" },
  { value: "DJF", label: "Djiboutian Franc" },
  { value: "DOP", label: "Dominican Peso" },
  { value: "XCD", label: "East Caribbean Dollar" },
  { value: "EGP", label: "Egyptian Pound" },
  { value: "GQE", label: "Equatorial Guinean Ekwele" },
  { value: "ERN", label: "Eritrean Nakfa" },
  { value: "EEK", label: "Estonian Kroon" },
  { value: "ETB", label: "Ethiopian Birr" },
  { value: "EUR", label: "Euro" },
  { value: "FKP", label: "Falkland Islands Pound" },
  { value: "FJD", label: "Fijian Dollar" },
  { value: "GMD", label: "Gambian Dalasi" },
  { value: "GEK", label: "Georgian Kupon Larit" },
  { value: "GEL", label: "Georgian Lari" },
  { value: "GHS", label: "Ghanaian Cedi" },
  { value: "GIP", label: "Gibraltar Pound" },
  { value: "GTQ", label: "Guatemalan Quetzal" },
  { value: "GNF", label: "Guinean Franc" },
  { value: "GYD", label: "Guyanaese Dollar" },
  { value: "HTG", label: "Haitian Gourde" },
  { value: "HNL", label: "Honduran Lempira" },
  { value: "HKD", label: "Hong Kong Dollar" },
  { value: "HUF", label: "Hungarian Forint" },
  { value: "ISK", label: "Icelandic Kr\u00f3na" },
  { value: "INR", label: "Indian Rupee" },
  { value: "IDR", label: "Indonesian Rupiah" },
  { value: "IRR", label: "Iranian Rial" },
  { value: "IQD", label: "Iraqi Dinar" },
  { value: "ILS", label: "Israeli New Shekel" },
  { value: "JMD", label: "Jamaican Dollar" },
  { value: "JPY", label: "Japanese Yen" },
  { value: "JOD", label: "Jordanian Dinar" },
  { value: "KZT", label: "Kazakhstani Tenge" },
  { value: "KES", label: "Kenyan Shilling" },
  { value: "KWD", label: "Kuwaiti Dinar" },
  { value: "KGS", label: "Kyrgystani Som" },
  { value: "LAK", label: "Laotian Kip" },
  { value: "LVL", label: "Latvian Lats" },
  { value: "LBP", label: "Lebanese Pound" },
  { value: "LSL", label: "Lesotho Loti" },
  { value: "LRD", label: "Liberian Dollar" },
  { value: "LYD", label: "Libyan Dinar" },
  { value: "LTL", label: "Lithuanian Litas" },
  { value: "MOP", label: "Macanese Pataca" },
  { value: "MKD", label: "Macedonian Denar" },
  { value: "MGA", label: "Malagasy Ariary" },
  { value: "MWK", label: "Malawian Kwacha" },
  { value: "MYR", label: "Malaysian Ringgit" },
  { value: "MVR", label: "Maldivian Rufiyaa" },
  { value: "MRO", label: "Mauritanian Ouguiya (1973\u20132017)" },
  { value: "MUR", label: "Mauritian Rupee" },
  { value: "MXN", label: "Mexican Peso" },
  { value: "MDL", label: "Moldovan Leu" },
  { value: "MNT", label: "Mongolian Tugrik" },
  { value: "MAD", label: "Moroccan Dirham" },
  { value: "MZN", label: "Mozambican Metical" },
  { value: "MMK", label: "Myanmar Kyat" },
  { value: "NAD", label: "Namibian Dollar" },
  { value: "NPR", label: "Nepalese Rupee" },
  { value: "ANG", label: "Netherlands Antillean Guilder" },
  { value: "TWD", label: "New Taiwan Dollar" },
  { value: "NZD", label: "New Zealand Dollar" },
  { value: "NIC", label: "Nicaraguan C\u00f3rdoba (1988\u20131991)" },
  { value: "NGN", label: "Nigerian Naira" },
  { value: "KPW", label: "North Korean Won" },
  { value: "NOK", label: "Norwegian Krone" },
  { value: "OMR", label: "Omani Rial" },
  { value: "PKR", label: "Pakistani Rupee" },
  { value: "PAB", label: "Panamanian Balboa" },
  { value: "PGK", label: "Papua New Guinean Kina" },
  { value: "PYG", label: "Paraguayan Guarani" },
  { value: "PEN", label: "Peruvian Sol" },
  { value: "PHP", label: "Philippine Peso" },
  { value: "PLN", label: "Polish Zloty" },
  { value: "QAR", label: "Qatari Rial" },
  { value: "RHD", label: "Rhodesian Dollar" },
  { value: "RON", label: "Romanian Leu" },
  { value: "ROL", label: "Romanian Leu (1952\u20132006)" },
  { value: "RUB", label: "Russian Ruble" },
  { value: "RWF", label: "Rwandan Franc" },
  { value: "SVC", label: "Salvadoran Col\u00f3n" },
  { value: "WST", label: "Samoan Tala" },
  { value: "SAR", label: "Saudi Riyal" },
  { value: "RSD", label: "Serbian Dinar" },
  { value: "SCR", label: "Seychellois Rupee" },
  { value: "SLL", label: "Sierra Leonean Leone" },
  { value: "SGD", label: "Singapore Dollar" },
  { value: "SKK", label: "Slovak Koruna" },
  { value: "SBD", label: "Solomon Islands Dollar" },
  { value: "SOS", label: "Somali Shilling" },
  { value: "ZAR", label: "South African Rand" },
  { value: "KRW", label: "South Korean Won" },
  { value: "LKR", label: "Sri Lankan Rupee" },
  { value: "SHP", label: "St. Helena Pound" },
  { value: "SDG", label: "Sudanese Pound" },
  { value: "SRD", label: "Surinamese Dollar" },
  { value: "SZL", label: "Swazi Lilangeni" },
  { value: "SEK", label: "Swedish Krona" },
  { value: "CHF", label: "Swiss Franc" },
  { value: "SYP", label: "Syrian Pound" },
  { value: "STD", label: "S\u00e3o Tom\u00e9 & Pr\u00edncipe Dobra (1977\u20132017)" },
  { value: "TJS", label: "Tajikistani Somoni" },
  { value: "TZS", label: "Tanzanian Shilling" },
  { value: "THB", label: "Thai Baht" },
  { value: "TOP", label: "Tongan Pa\u02bbanga" },
  { value: "TTD", label: "Trinidad & Tobago Dollar" },
  { value: "TND", label: "Tunisian Dinar" },
  { value: "TRY", label: "Turkish Lira" },
  { value: "TRL", label: "Turkish Lira (1922\u20132005)" },
  { value: "TMM", label: "Turkmenistani Manat (1993\u20132009)" },
  { value: "USD", label: "US Dollar" },
  { value: "UGX", label: "Ugandan Shilling" },
  { value: "UAH", label: "Ukrainian Hryvnia" },
  { value: "AED", label: "United Arab Emirates Dirham" },
  { value: "UYU", label: "Uruguayan Peso" },
  { value: "UZS", label: "Uzbekistani Som" },
  { value: "VUV", label: "Vanuatu Vatu" },
  { value: "VEB", label: "Venezuelan Bol\u00edvar (1871\u20132008)" },
  { value: "VEF", label: "Venezuelan Bol\u00edvar (2008\u20132018)" },
  { value: "VND", label: "Vietnamese Dong" },
  { value: "CHE", label: "WIR Euro" },
  { value: "CHW", label: "WIR Franc" },
  { value: "XOF", label: "West African CFA Franc" },
  { value: "YER", label: "Yemeni Rial" },
  { value: "ZMK", label: "Zambian Kwacha (1968\u20132012)" },
  { value: "ZWD", label: "Zimbabwean Dollar (1980\u20132008)" },
]

export const CURRENCY_IMPORT_SERVICE_OPTIONS = [
  { value: "fixerio", label: "Fixer.io (legacy)" },
  { value: "fixerio_apilayer", label: "Fixer Api (APILayer)" },
  { value: "currencyconverterapi", label: "Currency Converter API" },
]

export const CURRENCY_IMPORT_FREQUENCY_OPTIONS = [
  { value: "D", label: "Daily" },
  { value: "W", label: "Weekly" },
  { value: "M", label: "Monthly" },
]

/** The three `Start Time` selects (hours / minutes / seconds). */
export const TIME_HOUR_OPTIONS = [
  { value: "00", label: "00" },
  { value: "01", label: "01" },
  { value: "02", label: "02" },
  { value: "03", label: "03" },
  { value: "04", label: "04" },
  { value: "05", label: "05" },
  { value: "06", label: "06" },
  { value: "07", label: "07" },
  { value: "08", label: "08" },
  { value: "09", label: "09" },
  { value: "10", label: "10" },
  { value: "11", label: "11" },
  { value: "12", label: "12" },
  { value: "13", label: "13" },
  { value: "14", label: "14" },
  { value: "15", label: "15" },
  { value: "16", label: "16" },
  { value: "17", label: "17" },
  { value: "18", label: "18" },
  { value: "19", label: "19" },
  { value: "20", label: "20" },
  { value: "21", label: "21" },
  { value: "22", label: "22" },
  { value: "23", label: "23" },
]

export const TIME_MINSEC_OPTIONS = [
  { value: "00", label: "00" },
  { value: "01", label: "01" },
  { value: "02", label: "02" },
  { value: "03", label: "03" },
  { value: "04", label: "04" },
  { value: "05", label: "05" },
  { value: "06", label: "06" },
  { value: "07", label: "07" },
  { value: "08", label: "08" },
  { value: "09", label: "09" },
  { value: "10", label: "10" },
  { value: "11", label: "11" },
  { value: "12", label: "12" },
  { value: "13", label: "13" },
  { value: "14", label: "14" },
  { value: "15", label: "15" },
  { value: "16", label: "16" },
  { value: "17", label: "17" },
  { value: "18", label: "18" },
  { value: "19", label: "19" },
  { value: "20", label: "20" },
  { value: "21", label: "21" },
  { value: "22", label: "22" },
  { value: "23", label: "23" },
  { value: "24", label: "24" },
  { value: "25", label: "25" },
  { value: "26", label: "26" },
  { value: "27", label: "27" },
  { value: "28", label: "28" },
  { value: "29", label: "29" },
  { value: "30", label: "30" },
  { value: "31", label: "31" },
  { value: "32", label: "32" },
  { value: "33", label: "33" },
  { value: "34", label: "34" },
  { value: "35", label: "35" },
  { value: "36", label: "36" },
  { value: "37", label: "37" },
  { value: "38", label: "38" },
  { value: "39", label: "39" },
  { value: "40", label: "40" },
  { value: "41", label: "41" },
  { value: "42", label: "42" },
  { value: "43", label: "43" },
  { value: "44", label: "44" },
  { value: "45", label: "45" },
  { value: "46", label: "46" },
  { value: "47", label: "47" },
  { value: "48", label: "48" },
  { value: "49", label: "49" },
  { value: "50", label: "50" },
  { value: "51", label: "51" },
  { value: "52", label: "52" },
  { value: "53", label: "53" },
  { value: "54", label: "54" },
  { value: "55", label: "55" },
  { value: "56", label: "56" },
  { value: "57", label: "57" },
  { value: "58", label: "58" },
  { value: "59", label: "59" },
]
